[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de ambiente (definir no painel do Netlify)
# GMAIL_USER=seu-email@gmail.com
# GMAIL_APP_PASSWORD=sua-senha-de-app

# Headers de segurança
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS" 